listen-address=127.0.0.1,10.166.26.178
bind-interfaces
no-resolv
server=8.8.8.8
server=1.1.1.1
local=/team1.test/
address=/app.team1.test/10.166.26.178
address=/api.team1.test/10.166.26.178
local-ttl=30
log-queries
log-facility=/tmp/dnsmasq.log
